
import { LLMProvider } from "@/services/transcription";

// Mock function for generating a brief summary of a transcript
export const generateBriefSummary = async (text: string): Promise<string> => {
  // This function would normally use an AI model to generate a summary
  // For now, we'll return a mock summary
  
  await new Promise(resolve => setTimeout(resolve, 500)); // Simulate API delay
  
  if (!text || text.length < 10) {
    return "No transcript available to summarize.";
  }
  
  return `This is a brief summary of the medical consultation. The doctor discussed symptoms, reviewed medical history, and provided treatment recommendations.`;
};

// More comprehensive patient summary
export const generatePatientSummary = async (text: string, provider: LLMProvider = LLMProvider.OPENAI): Promise<string> => {
  // This function would normally use an AI model to generate a detailed patient summary
  // For now, we'll return a mock summary
  
  await new Promise(resolve => setTimeout(resolve, 800)); // Simulate API delay
  
  if (!text || text.length < 10) {
    return "No transcript available to summarize.";
  }
  
  // Generate different summaries based on provider for demonstration
  let summaryProvider = "AI";
  if (provider === LLMProvider.ANTHROPIC || provider === LLMProvider.CLAUDE) {
    summaryProvider = "Claude";
  } else if (provider === LLMProvider.OPENAI) {
    summaryProvider = "OpenAI";
  } else if (provider === LLMProvider.GEMINI) {
    summaryProvider = "Gemini";
  }
  
  return `## Patient Summary (Generated by ${summaryProvider})

### Chief Complaint
The patient reports a persistent cough for approximately one week with accompanying fatigue and low-grade fever.

### History of Present Illness
- One-week history of productive cough
- Low-grade fever measured at 99.5°F
- Increased fatigue
- Difficulty taking deep breaths without triggering cough
- No chest pain, but occasional chest tightness
- Self-medicating with over-the-counter cough syrup and acetaminophen with minimal relief

### Vital Signs
- Temperature: 99.5°F
- BP: 128/82
- Pulse: 88
- Respiratory Rate: 18
- O2 Saturation: 97% on room air

### Physical Findings
- Wheezing noted in lower lung fields bilaterally
- Increased respiratory effort
- Mild oropharyngeal erythema

### Assessment
- Acute bronchitis, likely viral
- Mild dehydration

### Plan
- Albuterol inhaler for bronchospasm
- Azithromycin course (Z-pak)
- Increased fluid intake
- Rest for 2-3 days
- Return if symptoms worsen
- Follow-up in one week`;
};
